export const REPOSITORY_SEARCH_REQUEST = "REPOSITORY_SEARCH_REQUEST";
export const REPOSITORY_SEARCH_SUCCESS = "REPOSITORY_SEARCH_SUCCESS";
export const REPOSITORY_SEARCH_FAIL = "REPOSITORY_SEARCH_FAIL";

export const REPOSITORY_ISSUES_REQUEST = "REPOSITORY_ISSUES_REQUEST";
export const REPOSITORY_ISSUES_SUCCESS = "REPOSITORY_ISSUES_SUCCESS";
export const REPOSITORY_ISSUES_FAIL = "REPOSITORY_ISSUES_FAIL";
